name: build

on: pull_request

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  generate-matrix:
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    runs-on: macos-latest
    steps:
      - uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false
      - uses: actions/checkout@v2
      - id: generate-matrix
        run: |
          brew tap homebrew/cask
          brew ruby -- "$(brew --repository homebrew/cask)/cmd/lib/generate-matrix.rb" "${{ github.event.pull_request.url }}"

  test:
    name: ${{ matrix.name }}
    needs: generate-matrix
    runs-on: macos-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    steps:
      - uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false
      - uses: actions/checkout@v2
      - run: |
          if ${{ !matrix.cask }}; then
            brew cask audit
            exit $?
          fi
          brew cask audit ${{ join(matrix.audit_args, ' ') }} '${{ matrix.cask.path }}'
